# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/version_1.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'protocols/version_1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protocols/version_1.proto\"}\n\x08\x45nvelope\x12 \n\nconnect_to\x18\x01 \x01(\x0b\x32\n.ConnectToH\x00\x12\x1e\n\tadd_pixel\x18\x02 \x01(\x0b\x32\t.AddPixelH\x00\x12$\n\x0c\x64\x65lete_pixel\x18\x03 \x01(\x0b\x32\x0c.DeletePixelH\x00\x42\t\n\x07payload\"\'\n\tConnectTo\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\"9\n\x08\x41\x64\x64Pixel\x12\x0e\n\x06x_cord\x18\x01 \x01(\r\x12\x0e\n\x06y_cord\x18\x02 \x01(\r\x12\r\n\x05\x63olor\x18\x03 \x01(\x07\"-\n\x0b\x44\x65letePixel\x12\x0e\n\x06x_cord\x18\x01 \x01(\r\x12\x0e\n\x06y_cord\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.version_1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVELOPE']._serialized_start=29
  _globals['_ENVELOPE']._serialized_end=154
  _globals['_CONNECTTO']._serialized_start=156
  _globals['_CONNECTTO']._serialized_end=195
  _globals['_ADDPIXEL']._serialized_start=197
  _globals['_ADDPIXEL']._serialized_end=254
  _globals['_DELETEPIXEL']._serialized_start=256
  _globals['_DELETEPIXEL']._serialized_end=301
# @@protoc_insertion_point(module_scope)
